name: Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Install packages (openapi-generator)
        run: deno task install

      - name: Generate
        run: deno task generate

      - name: Check
        run: deno check .

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: package-source
          path: src

  test:
    runs-on: ubuntu-latest
    needs: generate-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: client-js

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: package-source
          path: client-js/src

      - name: Clone kakomimasu/server
        uses: actions/checkout@v4
        with:
          repository: kakomimasu/server
          ref: main
          path: server

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Install server dependencies
        run: cd server && deno task cache

      - name: Init server database
        run: cd server && deno task db:init

      - name: Start server
        run: cd server && deno task start &

      - name: Wait for server to start
        run: |
          timeout 60s bash -c 'until curl -s http://localhost:8880; do sleep 1; done'

      - name: Run tests
        run: cd client-js && deno test -A .
