name: Deno Test

on: [push,pull_request]

jobs:
  check:
    uses: kakomimasu/kakomimasu.github.io/.github/workflows/dfl-check.yml@main
    with:
      config_file: deno.json

  test:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run test
        if: ${{ runner.os == 'Windows' }}
        run: |
          deno test -A src/
      - name: Run test
        if: ${{ runner.os != 'Windows' }}
        run: |
          deno test -A src/
